default:
  image: ruby:3.3
  cache:
    key: gems
    paths:
      - vendor/bundle
  before_script:
    - bundle config set --local path vendor/bundle
    - bundle install --jobs=$(nproc)

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - bundle exec standardrb

test:
  stage: test
  script:
    - bundle exec rake test
